name = "DarwinAtlas"
uuid = "d4a7f1e8-9c3b-4a5d-8e7f-2b9c1a6d3e4f"
authors = ["Demetrios Chiuratto Agourakis <demetrios@agourakis.med.br>"]
version = "2.0.0-alpha"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Quaternions = "94ee1d12-a955-5a0b-814e-a320396ab94c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
julia = "1.10"
BioSequences = "3"
CSV = "0.10"
DataFrames = "1"
FASTX = "2"
HTTP = "1"
JSON3 = "1"
Quaternions = "0.7"
